version: "3"

services:
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
      args:
        - OBAN_KEY_FINGERPRINT=${OBAN_KEY_FINGERPRINT}
        - OBAN_LICENSE_KEY=$OBAN_LICENSE_KEY
    volumes:
      - ./api:/app
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MIX_ENV: dev
      OBAN_KEY_FINGERPRINT: $OBAN_KEY_FINGERPRINT
      OBAN_LICENSE_KEY: $OBAN_LICENSE_KEY
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_HOSTNAME: database
  postgres:
    image: postgres:13
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
