export const {
  REACT_APP_API_BASE_URL,
  REACT_APP_BUGSNAG_API_KEY,
  REACT_APP_INTERCOM_ID,
  REACT_APP_PAYPAL_CLIENT_ID,
  REACT_APP_SOCKET_EP,
  REACT_APP_TWILIO_CID,
  REACT_APP_TWILIO_AUTH_TOKEN,
  REACT_APP_TWILIO_FROM_PHONE,
  REACT_APP_INTERCOM_API_KEY,
  REACT_APP_MIN_REBIRTH_MEMBERS,
} = process.env;
