use Mix.Config

# Configure your database
config :pl_connect, PlConnect.Repo,
  username: System.get_env("POSTGRES_USERNAME", "gigalixir_admin"),
  password: System.get_env("POSTGRES_PASSWORD", "pw-21c1026f-f7b4-41d9-88aa-4ee1e111db18"),
  database: System.get_env("POSTGRES_DATABASE", "d4e3b9c3-8af9-415e-a966-ce154b9fd5bb"),
  hostname: System.get_env("POSTGRES_HOSTNAME", "34.72.150.85"),
  show_sensitive_data_on_connection_error: true,
  pool_size: System.get_env("POSTGRES_POOL_SIZE", "10") |> Integer.parse() |> elem(0)

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :pl_connect, PlConnectWeb.Endpoint,
  http: [port: System.get_env("PORT", "4000") |> Integer.parse() |> elem(0)],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Do not print debug messages, usefull when testing oban
# config :logger, level: :info

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
