defmodule PlConnect.Repo.Migrations.MigrateResources46 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teams) do
      add :squad_size, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:teams) do
      remove :squad_size
    end
  end
end