defmodule PlConnect.Repo.Migrations.MigrateResources22 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:wallet_transactions) do
      modify :won_reward, :float, null: true
      modify :won, :boolean, null: true, default: nil
      modify :prev_wallet_balance, :float, null: true
      modify :bet_total_amount, :float, null: true
    end
  end

  def down do
    alter table(:wallet_transactions) do
      modify :bet_total_amount, :float, null: false
      modify :prev_wallet_balance, :float, null: false
      modify :won, :boolean, null: false, default: false
      modify :won_reward, :float, null: false
    end
  end
end