defmodule PlConnect.Repo.Migrations.MigrateResources45 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :wzranked_uno, :text
    end
  end

  def down do
    alter table(:users) do
      remove :wzranked_uno
    end
  end
end