defmodule PlConnect.Repo.Migrations.MigrateResources20 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :wallet, :map, default: %{funds: 100.0}
      add :phone, :text
    end
  end

  def down do
    alter table(:users) do
      remove :phone
      modify :wallet, :map, default: %{funds: 0.0}
    end
  end
end