defmodule PlConnect.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :wallet, :map, default: %{autogenerated_id: nil, funds: 100.0}
    end
  end

  def down do
    alter table(:users) do
      modify :wallet, :map, default: %{autogenerated_id: nil, funds: 1.0e3}
    end
  end
end
