defmodule PlConnect.Repo.Migrations.MigrateResources40 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do

    create table(:notes, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :text, :text, null: false
      add :inserted_at, :utc_datetime_usec, default: fragment("now()")
      add :user_id, references(:users, column: :id, name: "notes_user_id_fkey", type: :uuid)

      add :bet_history_id,
          references(:users_bet_history,
            column: :id,
            name: "notes_bet_history_id_fkey",
            type: :uuid
          )
    end
  end

  def down do
    drop constraint(:notes, "notes_bet_history_id_fkey")

    drop constraint(:notes, "notes_user_id_fkey")

    drop table(:notes)
  end
end