defmodule PlConnect.Repo.Migrations.MigrateResources17 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users_bet_history) do
      add :events, {:array, :map}, default: []
    end

    alter table(:users) do
      modify :wallet, :map, default: %{funds: 100.0}
      add :pl_core_user_id, :text
    end
  end

  def down do
    alter table(:users) do
      remove :pl_core_user_id
      modify :wallet, :map, default: %{funds: 0.0}
    end

    alter table(:users_bet_history) do
      remove :events
    end
  end
end
