defmodule PlConnect.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:users_bet_history), :bets_level_result, to: :user_bets_level_result
  end

  def down do
    rename table(:users_bet_history), :user_bets_level_result, to: :bets_level_result
  end
end
