defmodule PlConnect.Repo.Migrations.MigrateResources29 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:summary_stats) do
      modify :total_bets_placed_per_player, :float
      modify :total_matches_per_player, :float
    end
  end

  def down do
    alter table(:summary_stats) do
      modify :total_matches_per_player, :bigint
      modify :total_bets_placed_per_player, :bigint
    end
  end
end
