defmodule PlConnect.Repo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users_bet_history) do
      add :result_match_cod_id, :decimal
    end
  end

  def down do
    alter table(:users_bet_history) do
      remove :result_match_cod_id
    end
  end
end
