defmodule PlConnect.Repo.Migrations.MigrateResources18 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:wallet_transactions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true

      add :bet_history_id,
          references(:users_bet_history,
            column: :id,
            name: "wallet_transactions_bet_history_id_fkey",
            type: :uuid
          )

      add :team_id,
          references(:teams, column: :id, name: "wallet_transactions_team_id_fkey", type: :uuid)

      add :user_id,
          references(:users, column: :id, name: "wallet_transactions_user_id_fkey", type: :uuid)

      add :bet_total_amount, :float, null: false
      add :prev_wallet_balance, :float, null: false
      add :post_wallet_balance, :float, null: false
      add :won, :boolean, null: false, default: false
      add :type, :text, null: false
      add :status, :text, null: false
      add :inserted_at, :utc_datetime_usec, default: fragment("now()")
    end
  end

  def down do
    drop constraint(:wallet_transactions, "wallet_transactions_bet_history_id_fkey")

    drop constraint(:wallet_transactions, "wallet_transactions_team_id_fkey")

    drop constraint(:wallet_transactions, "wallet_transactions_user_id_fkey")

    drop table(:wallet_transactions)
  end
end
