defmodule PlConnect.Repo.Migrations.MigrateResources36 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :first_name, :text
      add :last_name, :text
      add :nationality, :text
      add :gender, :text
    end

    create unique_index(:users, [:phone], name: "users_unique_phone_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:phone], name: "users_unique_phone_index")

    alter table(:users) do
      remove :gender
      remove :nationality
      remove :last_name
      remove :first_name
    end
  end
end
