defmodule PlConnect.Repo.Migrations.MigrateResources27 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teams) do
      add :probabilities, :map
    end

    create table(:bet_values, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :game_mode, :text, null: false
      add :bet_category, :text, null: false
      add :type, :text, null: false
      add :level, :bigint, null: false, default: 1
      add :goal, :bigint, null: false, default: 1
      add :payout, :float, null: false, default: 1.0
      add :min_kda, :float, null: false, default: 1.0
      add :max_kda, :float, null: false, default: 1.0
      add :inserted_at, :utc_datetime_usec, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, default: fragment("now()")
    end
  end

  def down do
    drop table(:bet_values)

    alter table(:teams) do
      remove :probabilities
    end
  end
end