defmodule PlConnect.Repo.Migrations.MigrateResources15 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teams) do
      add :match_map, :text, null: false, default: "verdansk"
    end
  end

  def down do
    alter table(:teams) do
      remove :match_map
    end
  end
end
