defmodule PlConnect.Repo.Migrations.MigrateResources24 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teams) do
      add :private_users, {:array, :map}, default: nil
    end
  end

  def down do
    alter table(:teams) do
      remove :private_users
    end
  end
end
