defmodule PlConnect.Repo.Migrations.MigrateResources21 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:wallet_transactions) do
      add :won_reward, :float, null: true
    end
  end

  def down do
    alter table(:wallet_transactions) do
      remove :won_reward
    end
  end
end
