defmodule PlConnect.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :wallet, :map, default: %{autogenerated_id: nil, funds: 40.0}
    end

    # alter table(:teams) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :kills_bet_level
    #
    # end
    #
  end

  def down do
    # alter table(:teams) do
    # This is the `down` migration of the statement:
    #
    #     remove :kills_bet_level
    #
    #
    # add :kills_bet_level, :bigint, null: false, default: 1
    # end
    #
    alter table(:users) do
      modify :wallet, :map, default: %{autogenerated_id: nil, funds: 100.0}
    end
  end
end
