defmodule PlConnect.Repo.Migrations.MigrateResources23 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:wallet_transactions) do
      add :metadata, :map, default: %{}
    end
  end

  def down do
    alter table(:wallet_transactions) do
      remove :metadata
    end
  end
end