defmodule PlConnect.Repo.Migrations.MigrateResources43 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:wzranked_probabilities) do
      add :season, :text
    end
  end

  def down do
    alter table(:wzranked_probabilities) do
      remove :season
    end
  end
end