defmodule PlConnect.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :password_hash, :text, null: false
      add :xbl_platform_username, :text
      add :psn_platform_username, :text
      add :email, :text, null: false
      add :inserted_at, :utc_datetime_usec, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:psn_platform_username],
             name: "users_unique_psn_platform_username_index"
           )

    create unique_index(:users, [:xbl_platform_username],
             name: "users_unique_xbl_platform_username_index"
           )
  end

  def down do
    drop_if_exists unique_index(:users, [:xbl_platform_username],
                     name: "users_unique_xbl_platform_username_index"
                   )

    drop_if_exists unique_index(:users, [:psn_platform_username],
                     name: "users_unique_psn_platform_username_index"
                   )

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
