defmodule PlConnect.Repo.Migrations.MigrateResources30 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:summary_stats), :total_house_money_lost_to_house,
      to: :total_player_money_lost_to_house
  end

  def down do
    rename table(:summary_stats), :total_player_money_lost_to_house,
      to: :total_house_money_lost_to_house
  end
end
