defmodule PlConnect.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:teams, "teams_owner_id_fkey")

    alter table(:teams) do
      modify :placement_bet_level, :bigint, default: 0
      modify :damage_bet_level, :bigint, default: 0
      modify :main_bet_level, :bigint, default: 0

      modify :owner_id,
             references(:users,
               column: :id,
               name: "teams_owner_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:teams, "teams_owner_id_fkey")

    alter table(:teams) do
      modify :owner_id, references(:users, column: :id, name: "teams_owner_id_fkey", type: :uuid)
      modify :main_bet_level, :bigint, default: 1
      modify :damage_bet_level, :bigint, default: 1
      modify :placement_bet_level, :bigint, default: 1
    end
  end
end
