defmodule PlConnect.Repo.Migrations.MigrateResources19 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:features, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :description, :text, null: false
      add :domain, :text, null: false, default: "stop_bets"
      add :is_enabled, :boolean, null: false, default: true
      add :inserted_at, :utc_datetime_usec, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    create unique_index(:features, [:domain], name: "features_unique_domain_index")
  end

  def down do
    drop_if_exists unique_index(:features, [:domain], name: "features_unique_domain_index")

    drop table(:features)
  end
end
