defmodule PlConnect.Repo.Migrations.MigrateResources26 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:summary_stats, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :start_range, :utc_datetime
      add :end_range, :utc_datetime
      add :total_funds_in_player_accounts, :float
      add :total_registered_players, :bigint
      add :average_player_balance, :float
      add :inserted_at, :utc_datetime_usec, default: fragment("now()")
    end
  end

  def down do
    drop table(:summary_stats)
  end
end
