defmodule PlConnect.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :wallet, :map, default: %{funds: 40.0}
      add :cod_profile, :map
    end

    create table(:player_matches, primary_key: false) do
      add :user_id,
          references(:users, column: :id, name: "player_matches_user_id_fkey", type: :uuid)

      add :id, :bigserial, null: false, primary_key: true
      add :match_cod_id, :decimal, null: false
      add :platform_username, :text, null: false
      add :platform, :text
      add :match_map, :text
      add :match_type, :text
      add :match_teamcomp, :text
      add :match_date, :utc_datetime
      add :kills, :bigint
      add :damage, :bigint
      add :placement, :bigint
      add :json_response, :map, null: false
    end

    create unique_index(:player_matches, [:match_cod_id, :platform, :platform_username],
             name: "player_matches_unique_player_match_index"
           )
  end

  def down do
    drop_if_exists unique_index(:player_matches, [:match_cod_id, :platform, :platform_username],
                     name: "player_matches_unique_player_match_index"
                   )

    drop table(:player_matches)

    alter table(:users) do
      remove :cod_profile
      modify :wallet, :map, default: %{autogenerated_id: nil, funds: 40.0}
    end
  end
end
