defmodule PlConnect.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teams) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :bet_level

      add :main_bet_level, :bigint, null: false, default: 1
      add :damage_bet_level, :bigint, null: false, default: 1
      add :placement_bet_level, :bigint, null: false, default: 1
      add :kills_bet_level, :bigint, null: false, default: 1
    end
  end

  def down do
    alter table(:teams) do
      remove :kills_bet_level
      remove :placement_bet_level
      remove :damage_bet_level
      remove :main_bet_level
      # This is the `down` migration of the statement:
      #
      #     remove :bet_level
      #

      add :bet_level, :bigint, null: false, default: 4
    end
  end
end
