defmodule PlConnect.Repo.Migrations.MigrateResources35 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :flags, :map,
        default: %{disallow_bets: false, disallow_deposits: false, multiply_factor: 0.15}
    end

    alter table(:features) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      # remove :is_enabled

      add :type, :text, null: false, default: "string"
      add :value, :text, null: false, default: "true"
    end
  end

  def down do
    alter table(:features) do
      remove :value
      remove :type
      # This is the `down` migration of the statement:
      #
      #     remove :is_enabled
      #

      # add :is_enabled, :boolean, null: false, default: true
    end

    alter table(:users) do
      modify :flags, :map, default: %{disallow_bets: false, disallow_deposits: false}
    end
  end
end