defmodule PlConnect.Repo.Migrations.MigrateResources28 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:summary_stats) do
      add :total_new_players, :bigint
      add :total_new_players_completed_a_game, :bigint
      add :total_matches_played, :bigint
      add :total_matches_per_player, :bigint
      add :total_bets_placed, :bigint
      add :total_bets_placed_per_player, :bigint
      add :total_entry_fees, :float
      add :total_house_money_won_to_players, :float
      add :total_house_money_lost_to_house, :float
      add :total_net_performance, :float
      add :total_percent_house_handle, :float
      add :entry_fees_per_player, :float
      add :total_house_money_won_per_player, :float
      add :total_house_money_lost_per_player, :float
      add :total_net_performance_per_player, :float
    end
  end

  def down do
    alter table(:summary_stats) do
      remove :total_net_performance_per_player
      remove :total_house_money_lost_per_player
      remove :total_house_money_won_per_player
      remove :entry_fees_per_player
      remove :total_percent_house_handle
      remove :total_net_performance
      remove :total_house_money_lost_to_house
      remove :total_house_money_won_to_players
      remove :total_entry_fees
      remove :total_bets_placed_per_player
      remove :total_bets_placed
      remove :total_matches_per_player
      remove :total_matches_played
      remove :total_new_players_completed_a_game
      remove :total_new_players
    end
  end
end
