defmodule PlConnect.Repo.Migrations.MigrateResources48 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_events_info, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :user_id, :uuid
      add :event_name, :text
      add :value, :text
      add :additional_info, :map, default: %{}
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    drop table(:user_events_info)
  end
end