defmodule PlConnect.Repo.Migrations.MigrateResources31 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :refresh_berbix_token, :text
      add :date_of_birth, :text
      add :family_name, :text
      add :given_name, :text
      add :middle_name, :text
      add :verified_document, :text
    end
  end

  def down do
    alter table(:users) do
      remove :verified_document
      remove :middle_name
      remove :given_name
      remove :family_name
      remove :date_of_birth
      remove :refresh_berbix_token
    end
  end
end