defmodule PlConnect.Repo.Migrations.MigrateResources37 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :step_register, :text, null: false, default: "step_3"
    end
  end

  def down do
    alter table(:users) do
      remove :step_register
    end
  end
end
