defmodule PlConnect.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :wallet, :map, null: false, default: %{autogenerated_id: nil, funds: 1.0e3}
    end

    alter table(:teams_users) do
      add :lobby_platform, :text, null: false
    end

    alter table(:teams) do
      add :bets, :map
      add :bet_level, :bigint, null: false, default: 4
    end
  end

  def down do
    alter table(:teams) do
      remove :bet_level
      remove :bets
    end

    alter table(:teams_users) do
      remove :lobby_platform
    end

    alter table(:users) do
      remove :wallet
    end
  end
end
