defmodule PlConnect.Repo.Migrations.MigrateResources49 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :battlenet_platform_username, :text
      add :battlenet_cod_profile, :map
    end

    create unique_index(:users, [:battlenet_platform_username],
             name: "users_unique_battlenet_platform_username_index"
           )
  end

  def down do
    drop_if_exists unique_index(:users, [:battlenet_platform_username],
                     name: "users_unique_battlenet_platform_username_index"
                   )

    alter table(:users) do
      remove :battlenet_cod_profile
      remove :battlenet_platform_username
    end
  end
end