defmodule PlConnect.Repo.Migrations.MigrateResources50 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:rebirth_lines, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :mean_kills_sum, :float
      add :advantage, :text, null: false
      add :team_size, :text, null: false
      add :kills_bet_1, :bigint, default: 1
      add :kills_bet_2, :bigint, default: 1
      add :kills_bet_3, :bigint, default: 1
      add :payout_bet_1, :float
      add :payout_bet_2, :float
      add :payout_bet_3, :float
      add :version, :text, default: "1.0"
      add :inserted_at, :utc_datetime_usec, default: fragment("now()")
    end
  end

  def down do
    drop table(:rebirth_lines)
  end
end