version: "3"

services:
  app:
    depends_on:
      - database
    image: pl-connect/api:latest
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MIX_ENV: dev

      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_HOSTNAME: database
      BERBIX_USERNAME: secret_test_NBoNkEvU5fp7QO2oAfiqCm1rY7Xzru6g
      BERBIX_TEMPLATE: tpk_rOxbVoRLxxFD6Mx0TnjCPY1T5fdBqNDu
      BERBIX_ORG_ID: 5663461317017600
      RETOOL_TOKEN: 1576fcd4328a4e5988b52257fec30b26511426ea35d4438ba03a93bad168b22d
      PAYPAL_CLIENT:
      PAYPAL_SECRET:
      PAYPAL_URL: https://api-m.sandbox.paypal.com
      TOURNAMENTS_URL: http://pl-dev-be-pl-tournaments-1366517835.us-east-1.elb.amazonaws.com
#      TOURNAMENTS_TOKEN: 1576fcd4328a4e5PzaCzmM1Nic3nKLpt5H8e0MGax7niyOxtQukB5mtiHzAN3Csfba03a93bad168b22d
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
